networks:
  default:

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - default    
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    networks:
      - default      
    volumes:
      - ./db/01.sql:/tmp/01.sql
      - ./db/02.sql:/tmp/02.sql
      - ./db/init.sh:/tmp/init.sh
    command: /bin/bash ./tmp/init.sh      
