###
POST http://localhost:3000/customers
content-type: application/json

{
    "name": "Marcilia",
    "document": "4155555555",
    "email":"marcilia@gmail.com"
}

###

GET http://localhost:3000/customers

###
GET http://localhost:3000/customers/4155555555