###
POST http://localhost:3000/customers
content-type: application/json

{
    "name": "Marcilia",
    "document": "12345678911",
    "email":"marcilia@gmail.com"
}

###

GET http://localhost:3000/customers

###
GET http://localhost:3000/customers/12345678911

###
GET http://localhost:3000/produtos

###
GET http://localhost:3000/produtos/categorias

###
POST http://localhost:3000/produtos
content-type: application/json

{
    "nome": "X-Tudo",
    "categoriaId": "Lanche",
    "preco": "2000",
    "descricao": "Lanche completo",
    "ativo":"true"
}

###
POST http://localhost:3000/orders
content-type: application/json

{
  "customerId": "2167EE43-6BA1-40FE-82DC-0C32D273FF09",
  "combos": [
    {
      "sandwichId": "PROD0001",
       "dessertId": "PROD0002"
    } 
  ]
}

###
POST http://localhost:3000/orders
content-type: application/json

{
  "customerId": "2167EE43-6BA1-40FE-82DC-0C32D273FF09",
  "combos": [
    {
      "sandwichId": "PROD0001",
      "dessertId": "PROD0002",
      "drinkId": "PROD0004",
      "accompanimentId": "PROD0003"
    },
    {
      "sandwichId": "PROD0001",
      "drinkId": "PROD0004"
    },
    {
      "dessertId": "PROD0002",
      "accompanimentId": "PROD0003"
    }
  ]
}

###
GET http://localhost:3000/orders

###
GET http://localhost:3000/orders/5d2301a3-7f41-416f-ac15-6d3cad6aa06f

###
GET http://localhost:3000/orders/state/CREATED

###
PUT http://localhost:3000/orders/876a5d56-037f-4310-ba1f-d80afaa49b60/state
content-type: application/json

{
  "status": "DELIVERED"
}

###
PUT http://localhost:3000/orders/77ed7a35-5326-4324-8eef-60078c1bc580/checkout
content-type: application/json

{
  "qrCode": "TESTEPAGAMENTO"
}