apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-restaurant-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dog-restaurant-api
  template:
    metadata:
      labels:
        app: dog-restaurant-api
    spec:
      hostname: dog-restaurant-api
      serviceAccountName: dog-service-account
      containers:
      - name: dog-restaurant-api
        image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/dog-restaurant-api:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: AWS_REGION
          value: "us-east-1"   
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: dbhost
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbpassword
              key: DB_PASSWORD        
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: dbuser
              key: DB_USER                           
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: dbname
              key: DB_NAME          