apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-dog-restaurant-api
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: dog-restaurant-api
  type: LoadBalancer    
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-mssql
spec:
  ports:
  - port: 1433
    targetPort: 1433
  selector:
    app: mssql
  type: LoadBalancer    