apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: dog-node-port
  labels:
    app: dog-restaurant-api
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /api
spec:
  type: NodePort
  selector:
    app: dog-restaurant-api
  ports:
    - port: 80
      targetPort: 80