apiVersion: v1
kind: Service
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  ports:
  - port: 1433
    name: mssql
  clusterIP: None
  selector:
    app: mssql
---
apiVersion: v1
kind: Service
metadata:
  name: dog-restaurant-api
  labels:
    app: dog-restaurant-api
spec:
  type: NodePort
  ports:
  - port: 3000
    name: dog-restaurant-api
  clusterIP: None
  selector:
    app: dog-restaurant-api
