apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-restaurant-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dog-restaurant-api
  template:
    metadata:
      labels:
        app: dog-restaurant-api
    spec:
      hostname: dog-restaurant-api
      serviceAccountName: dog-service-account
      containers:
      - name: dog-restaurant-api
        image: <ACCOUNT>.dkr.ecr.us-east-1.amazonaws.com/dog-restaurant-api:<TAG>
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: AWS_REGION
          value: ''  
        - name: DB_NAME
          value: ''
        - name: DB_PORT
          value: ''
        - name: DB_USER
          value: ''
        - name: DB_PASSWORD
          value: ''
        - name: DB_HOST
          value: ''