apiVersion: v1
kind: Service
metadata:
  name: dog-restaurant-api
  namespace: default
  labels:
    app: dog-restaurant-api
spec:
  selector:
    app: dog-restaurant-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP      